(function(){'use strict';var n;function q(a,b,d){"x"!==b[0]?a.setAttribute(b,d):"m"===b[1]&&"l"===b[2]?a.setAttributeNS("http://www.w3.org/XML/1998/namespace",b,d):"l"===b[1]&&"i"===b[2]?a.setAttributeNS("http://www.w3.org/1999/xlink",b,d):a.setAttribute(b,d)}function t(a,b,d){this.b=a;this.A=b;this.v=void 0;this.j=d;this.s=this.f=this.o=this.B=this.I=this.H=void 0}n=t.prototype;n.key=function(a){this.v=a;return this};function u(a,b){a.j=b;return a}function v(a,b){a.H=b;return a}
n.style=function(a){this.I=a;return this};n.className=function(a){this.B=a;return this};n.children=function(a){this.o=a;return this};function aa(a,b){a.b|=16;a.o=b;return a}n.value=function(a){this.b|=512;this.o=a;return this};n.checked=function(a){this.b|=1024;this.o=a;return this};function w(a,b){return a.b===b.b&&a.A===b.A&&a.v===b.v}
n.create=function(a){var b=this.b;this.b&=-65;0!==(b&1)?this.f=document.createTextNode(this.j):0!==(b&2)?0===(b&131072)?this.f=0===(b&32768)?document.createElement(this.A):document.createElementNS("http://www.w3.org/2000/svg",this.A):this.f=this.A.createElement():(a=y(this.A,a,this.j,this.o),this.f=a.element,this.s=a)};
function z(a,b,d){var c,e,g,f,h=a.b,k;if(0!==(h&10)){k=a.f;if(0===(h&262144)){var m=a.j;if(void 0!==m)for(f=Object.keys(m),c=0,e=f.length;c<e;c++)g=f[c],k[g]=m[g];if(void 0!==a.H)for(f=Object.keys(a.H),c=0,e=f.length;c<e;c++)g=f[c],q(k,g,a.H[g]);void 0!==a.I&&(0===(h&32768)?k.style.cssText=a.I:k.setAttribute("style",a.I));void 0!==a.B&&(0===(h&32768)?k.className=a.B:k.setAttribute("class",a.B))}else 0===(h&8)?a.A.update(k,void 0,a.j):b.w.A.update(k,void 0,a.j);g=a.o;if(void 0!==g)if(0===(a.b&1536))if("string"===
typeof g)k.textContent=g;else for(c=0,e=g.length;c<e;c++)a.D(g[c],void 0,b,d);else 0!==(a.b&512)?a.f.value=a.o:a.f.checked=a.o}else 0!==(h&4)&&(k=a.f,void 0!==a.B&&(0===(h&32768)?k.className=a.B:k.setAttribute("class",a.B)),0===(d&1)&&a.s.update())}
function A(a,b,d){var c=a.b,e=a.o;a.f=b;if(0!==(c&4))e=a.A,b=new B(12,e,b,d,a.j,a.o),void 0!==e.a&&e.a(b),b.K(),b=a.s=b,b.setData(a.j),b.V(a.o),b.update();else if(0!==(a.b&10)){if(void 0!==a.j)for(var g=Object.keys(a.j),c=0;c<g.length;c++){var f=g[c];b[f]=a.j[f]}if(void 0!==e&&"string"!==typeof e&&0<e.length){for(a=b.firstChild;8===a.nodeType;)g=a,a=a.nextSibling,b.removeChild(g);for(c=0;c<e.length;c++)for(A(e[c],a,d),a=a.nextSibling;null!==a&&8===a.nodeType;)g=a,a=a.nextSibling,b.removeChild(g)}}}
n.u=function(a,b,d){var c=this.f,e=this.b,g;a.f=c;if(0!==(e&1))this.j!==a.j&&(this.f.nodeValue=a.j);else if(0!==(e&10)){if(0===(e&262144)){if(this.j!==a.j)if(0===(this.b&256)){g=this.j;var f=a.j,h=Object.keys(g),k,m;for(m=0;m<h.length;m++){k=h[m];var l=f[k];g[k]!==l&&(c[k]=l)}}else if(g=this.j,f=a.j,void 0!==g)if(void 0===f)for(k=Object.keys(g),h=0;h<k.length;h++)c[k[h]]=void 0;else{k=Object.keys(g);for(h=0;h<k.length;h++)m=k[h],f.hasOwnProperty(m)?(l=f[m],g[m]!==l&&(c[m]=l)):c[m]=void 0;k=Object.keys(f);
for(h=0;h<k.length;h++)m=k[h],g.hasOwnProperty(m)||(c[m]=f[m])}else if(void 0!==f)for(k=Object.keys(f),h=0;h<k.length;h++)m=k[h],c[m]=f[m];if(this.H!==a.H)if(0===(this.b&128))for(g=this.H,f=a.H,h=Object.keys(g),m=0;m<h.length;m++)k=h[m],l=f[k],g[k]!==l&&q(c,k,l);else if(g=this.H,f=a.H,void 0!==g)if(void 0===f)for(k=Object.keys(g),h=0;h<k.length;h++)c.removeAttribute(k[h]);else{k=Object.keys(g);for(h=0;h<k.length;h++)m=k[h],f.hasOwnProperty(m)?(l=f[m],g[m]!==l&&q(c,m,l)):c.removeAttribute(m);k=Object.keys(f);
for(h=0;h<k.length;h++)m=k[h],g.hasOwnProperty(m)||q(c,m,f[m])}else if(void 0!==f)for(k=Object.keys(f),h=0;h<k.length;h++)m=k[h],q(c,m,f[m]);this.I!==a.I&&(g=void 0===a.I?"":a.I,0===(e&32768)?c.style.cssText=g:c.setAttribute("style",g));this.B!==a.B&&(g=void 0===a.B?"":a.B,0===(e&32768)?c.className=g:c.setAttribute("class",g))}else this.j!==a.j&&(0===(e&8)?this.A.update(c,this.j,a.j):b.w.A.update(c,this.j,a.j));if(0===(this.b&1536)){if(this.o!==a.o)if(c=this.o,a=a.o,f=0,h=!1,"string"===typeof c)if(void 0===
a)this.f.removeChild(this.f.firstChild);else if("string"===typeof a)(d=this.f.firstChild)?d.nodeValue=a:this.f.textContent=a;else for(this.f.removeChild(this.f.firstChild);f<a.length;)this.D(a[f++],void 0,b,d);else if("string"===typeof a){if(void 0!==c)for(;f<c.length;)this.F(c[f++]);this.f.textContent=a}else if(void 0!==c&&0!==c.length)if(void 0===a||0===a.length)for(;f<c.length;)this.F(c[f++]);else if(1===c.length&&1===a.length)e=c[0],g=a[0],w(e,g)?e.u(g,b,d):this.N(g,e,b,d);else if(1===c.length){e=
c[0];if(0===(this.b&16))for(;f<a.length;){g=a[f++];if(w(e,g)){e.u(g,b,d);h=!0;break}this.D(g,e.f,b,d)}else for(;f<a.length;){g=a[f++];if(e.v===g.v){e.u(g,b,d);h=!0;break}this.D(g,e.f,b,d)}if(h)for(;f<a.length;)this.D(a[f++],void 0,b,d);else this.F(e)}else if(1===a.length){g=a[0];if(0===(this.b&16))for(;f<c.length;){e=c[f++];if(w(e,g)){e.u(g,b,d);h=!0;break}this.F(e)}else for(;f<c.length;){e=c[f++];if(e.v===g.v){e.u(g,b,d);h=!0;break}this.F(e)}if(h)for(;f<c.length;)this.F(c[f++]);else this.D(g,void 0,
b,d)}else if(0===(this.b&16)){e=f=0;h=c.length-1;for(g=a.length-1;f<=h&&e<=g;){k=c[f];m=a[e];if(!w(k,m))break;f++;e++;k.u(m,b,d)}for(;f<=h&&e<=g;){k=c[h];m=a[g];if(!w(k,m))break;h--;g--;k.u(m,b,d)}for(;f<=h&&e<=g;)k=c[f++],m=a[e++],w(k,m)?k.u(m,b,d):this.N(m,k,b,d);if(f<=h){do this.F(c[f++]);while(f<=h)}else if(e<=g){c=g+1;c=c<a.length?a[c].f:void 0;do this.D(a[e++],c,b,d);while(e<=g)}}else{var p=0,e=0,h=c.length-1;k=a.length-1;f=c[p];g=a[e];var l=c[h],r=a[k],x=!1,G;m=0;a:do{for(x=!0;f.v===g.v;){f.u(g,
b,d);p++;e++;if(p>h||e>k)break a;f=c[p];g=a[e];x=!1}for(;l.v===r.v;){l.u(r,b,d);h--;k--;if(p>h||e>k)break a;l=c[h];r=a[k];x=!1}for(;f.v===r.v;){f.u(r,b,d);f=k+1;f=f<a.length?a[f].f:void 0;this.M(r,f);p++;k--;if(p>h||e>k)break a;f=c[p];r=a[k];x=!1;continue a}for(;l.v===g.v;){l.u(g,b,d);this.M(g,f.f);h--;e++;if(p>h||e>k)break a;l=c[h];g=a[e];x=!1;continue a}}while(!x&&p<=h&&e<=k);if(p>h)for(f=k+1,f=f<a.length?a[f].f:void 0;e<=k;)this.D(a[e++],f,b,d);else if(e>k)for(;p<=h;)this.F(c[p++]);else{x=h-p+
1;f=k-e+1;g=Array(f);for(l=0;l<f;l++)g[l]=-1;var M=!1,N=0;if(16>=x*f)for(l=p;l<=h;l++){for(var H=!0,r=c[l],p=e;p<=k;p++)if(G=a[p],r.v===G.v){g[p-e]=l;m>p?M=!0:m=p;r.u(G,b,d);H=!1;break}H&&(this.F(r),N++)}else{H=new Map;for(l=e;l<=k;l++)r=a[l],H.set(r.v,l);for(l=p;l<=h;l++)r=c[l],p=H.get(r.v),void 0!==p?(G=a[p],g[p-e]=l,m>p?M=!0:m=p,r.u(G,b,d)):(this.F(r),N++)}if(M){h=g.slice(0);c=[];c.push(0);k=0;for(m=g.length;k<m;k++)if(-1!==g[k])if(l=c[c.length-1],g[l]<g[k])h[k]=l,c.push(k);else{l=0;for(p=c.length-
1;l<p;)r=(l+p)/2|0,g[c[r]]<g[k]?l=r+1:p=r;g[k]<g[c[l]]&&(0<l&&(h[k]=c[l-1]),c[l]=k)}l=c.length;for(p=c[l-1];0<l--;)c[l]=p,p=h[p];p=c.length-1;for(l=f-1;0<=l;l--)-1===g[l]?(f=l+e,r=a[f],f+=1,f=f<a.length?a[f].f:void 0,this.D(r,f,b,d)):0>p||l!==c[p]?(f=l+e,r=a[f],f+=1,f=f<a.length?a[f].f:void 0,this.M(r,f)):p--}else if(x-N!==f)for(l=f-1;0<=l;l--)-1===g[l]&&(f=l+e,r=a[f],f+=1,f=f<a.length?a[f].f:void 0,this.D(r,f,b,d))}}else if(void 0!==a&&0<a.length)for(f=0;f<a.length;f++)this.D(a[f],void 0,b,d)}else 0!==
(e&512)?c.value!==a.o&&(c.value=a.o):c.checked!==a.o&&(c.checked=a.o)}else this.B!==a.B&&(g=void 0===a.B?"":a.B,0===(e&32768)?c.className=g:c.setAttribute("class",g)),b=a.s=this.s,0===(d&2)&&(b.setData(a.j),b.V(a.o),b.update())};n.J=function(){if(0===(this.b&4)){var a=this.o;if(void 0!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)a[b].J()}else this.s.J()};n.K=function(){0!==(this.b&4)&&this.s.J()};
n.detach=function(){if(0===(this.b&4)){var a=this.o;if(void 0!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)a[b].detach()}else this.s.detach()};n.L=function(){if(0===(this.b&2048))if(0!==(this.b&4))this.s.L();else{if(void 0!==this.o){var a=this.o;if("string"!==typeof a)for(var b=0;b<a.length;b++)a[b].L()}}else this.detach()};
n.D=function(a,b,d,c){if(0!==(this.b&32)&&void 0!==this.s.w.D)this.s.w.D(this.s,this.f,a,b);else{var e=this.f;void 0===a.f?(a.create(d),e.insertBefore(a.f,b),a.K(),z(a,d,c)):(e.insertBefore(a.f,b),a.J())}};n.N=function(a,b,d,c){if(0!==(this.b&32)&&void 0!==this.s.w.N)this.s.w.N(this.s,this.f,a,b);else{var e=this.f;void 0===a.f?(a.create(d),e.replaceChild(a.f,b.f),a.K(),z(a,d,c)):(e.replaceChild(a.f,b.f),a.J());b.L()}};
n.M=function(a,b){0!==(this.b&32)&&void 0!==this.s.w.M?this.s.w.M(this.s,this.f):this.f.insertBefore(a.f,b)};n.F=function(a){0!==(this.b&32)&&void 0!==this.s.w.F?this.s.w.F(this.s):(this.f.removeChild(a.f),a.L())};function C(a){return new t(2,a,void 0)}function D(){return new t(8,void 0,void 0)}function ba(a){this.c=new MutationObserver(a);this.a=document.createTextNode("");this.c.observe(this.a,{characterData:!0})}
function ca(a){var b=this.a="__kivi"+Math.random();window.addEventListener("message",function(d){d.source===window&&d.data===b&&a()})}function E(){this.b=0;this.c=[];this.a=this.l=this.G=this.g=void 0}function F(a){var b=I();if(0===(a.h&256)){a.h|=256;var d=a.depth;for(b.b|=1;d>=b.c.length;)b.c.push(void 0);var c=b.c[d];void 0===c?b.c[d]=[a]:c.push(a)}}E.prototype.write=function(a){this.b|=2;void 0===this.g&&(this.g=[]);this.g.push(a)};E.prototype.focus=function(a){this.a=a};
function J(a){0===(a.b&8)&&(a.b|=8,requestAnimationFrame(a.ea))}function I(){var a=K;J(a);return a.G}function da(){var a=K;if(0!==(a.b&32))return 0;var b=a.aa-performance.now();return 0>=b?(a.b|=32,0):b}
var K=new function(){var a=this;this.ga=function(){a.b|=1;for(a.c=Date.now();0<a.l.length;){var b=a.l;a.l=[];for(var d=0;d<b.length;d++)b[d]()}a.a++;a.b&=-4};this.fa=function(){a.b&=-5;a.b|=1;a.c=Date.now();var b=a.$;a.$=[];for(var d=0;d<b.length;d++)b[d]();a.a++;a.b&=-2};this.ea=function(b){var d=a.ha,c;a.b&=-41;a.b|=1;a.c=Date.now();0!==(a.b&16)&&(a.aa=b+0);var e=a.G;a.G=a.g;a.g=e;for(b=0;b<d.length;b++)c=d[b],c.h|=8;do{for(;0!==(e.b&4);)for(e.b&=-5,c=e.G,e.G=void 0,b=0;b<c.length;b++)c[b]();for(;0!==
(e.b&3);){if(0!==(e.b&1)){e.b&=-2;var g=e.c;for(b=0;b<g.length;b++){var f=g[b];if(void 0!==f)for(g[b]=void 0,c=0;c<f.length;c++)f[c].update()}}if(0!==(e.b&2))for(e.b&=-3,c=e.g,e.g=void 0,b=0;b<c.length;b++)c[b]()}b=0;for(c=d.length;b<c;)g=d[b++],0===(g.h&16)?(g.h&=-33,b===c?d.pop():d[--b]=d.pop()):g.update()}while(0!==(e.b&7));for(;0!==(e.b&8);)for(e.b&=-9,c=e.l,e.l=void 0,b=0;b<c.length;b++)c[b]();void 0!==e.a&&(e.a.constructor===t?e.a.f.focus():e.a.focus(),e.a=void 0);0<d.length&&J(a);a.a++;a.b&=
-2};this.b=0;this.a=1;this.c=0;this.l=[];this.$=[];this.g=new E;this.G=new E;this.ha=[];new ba(this.ga);new ca(this.fa);this.aa=0};function L(a,b,d,c){this.b=a;this.O=b;this.c=d;this.a=c}function O(a){0!==(a.b&1)?a.c.i():a.a()}function P(){this.G=K.a;this.c=this.l=this.a=this.g=void 0}n=P.prototype;n.subscribe=function(a){a=new L(0,this,void 0,a);Q(this,a);return a};n.P=function(a){a=new L(2,this,void 0,a);R(this,a);return a};
n.i=function(){var a=K.a;if(this.G<a){this.G=a;if(void 0!==this.g)O(this.g);else if(void 0!==this.a)for(a=0;a<this.a.length;a++)O(this.a[a]);if(void 0!==this.l)O(this.l);else if(void 0!==this.c)for(a=0;a<this.c.length;a++)O(this.c[a])}};function Q(a,b){void 0!==a.g?(a.a=[a.g,b],a.g=void 0):void 0===a.a?a.g=b:a.a.push(b)}function R(a,b){void 0!==a.l?(a.c=[a.l,b],a.l=void 0):void 0===a.c?a.l=b:a.c.push(b)}
n.S=function(a){this.g===a?this.g=void 0:1===this.a.length?this.a=void 0:this.a[this.a.indexOf(a)]=this.a.pop()};n.T=function(a){this.l===a?this.l=void 0:1===this.c.length?this.c=void 0:this.c[this.c.indexOf(a)]=this.c.pop()};function S(){this.b=0;this.A="div";this.ca=this.ba=this.W=this.da=this.Z=this.a=this.X=this.Y=void 0}n=S.prototype;n.tagName=function(a){this.A=a;return this};n.setData=function(a){this.Y=a;return this};n.V=function(a){this.X=a;return this};function T(a,b){a.a=b;return a}
n.update=function(a){this.Z=a;return this};n.K=function(a){this.W=a;return this};function U(a,b){return new t(4,a,b)}function y(a,b,d,c){var e;0===(a.b&131072)?e=0===(a.b&32768)?document.createElement(a.A):document.createElementNS("http://www.w3.org/2000/svg",a.A):e=a.A.createElement();b=new B(8,a,e,b,d,c);0!==(a.b&1)&&(e.R=b);void 0!==a.a&&a.a(b);return b}
function B(a,b,d,c,e,g){this.h=a;this.w=b;this.element=d;this.depth=void 0===c?0:c.depth+1;this.state=void 0;this.data=e;this.children=g;this.a=0===(a&65536)?void 0:d.getContext("2d");this.g=this.c=void 0}n=B.prototype;n.setData=function(a){var b=this.w.Y;if(void 0===b){if(0!==(this.h&128)||this.data!==a)this.data=a,this.h|=8}else b(this,a)};n.V=function(a){var b=this.w.X;void 0===b?this.children!==a&&(this.children=a,this.h|=8):b(this,a)};
n.update=function(){10===(this.h&10)&&(0===(K.b&16)||0!==(this.h&512)||0<da()?(this.w.Z(this),this.h&=-269):F(this))};n.u=function(a,b){b=void 0===b?0:b;void 0===this.a?(a.s=this,0!==(this.h&4)?(A(a,this.element,this),this.h&=-5):(a.f=this.element,z(a,this,b))):this.a.u(a,this,b);this.a=a};n.i=function(){if(0===(this.h&9)){this.h|=8;ea(this);F(this);var a=this.w.da;void 0!==a&&a(this)}};n.J=function(){this.K();void 0!==this.a&&0===(this.h&65536)&&this.a.J()};
n.K=function(){this.h|=2;var a=this.w.W;void 0!==a&&a(this)};n.detach=function(){void 0!==this.a&&0===(this.h&65536)&&this.a.detach();fa(this)};function fa(a){a.h&=-19;var b=a.c;if(void 0!==b)if(b.constructor===L)b.O.S(b);else for(var d=0;d<b.length;d++){var c=b[d];c.O.S(c)}a.c=void 0;ea(a);b=a.w.ba;void 0!==b&&b(a)}n.L=function(){this.h|=1;void 0!==this.a&&0===(this.h&65536)&&this.a.L();0!==(this.h&2)&&fa(this);var a=this.w.ca;void 0!==a&&a(this)};
n.subscribe=function(a){var b=new L(1,a,this,void 0);Q(a,b);a=this.c;void 0===a?this.c=b:a.constructor===L?this.c=[this.c,b]:a.push(b)};n.P=function(a){var b=new L(3,a,this,void 0);R(a,b);a=this.g;void 0===a?this.g=b:a.constructor===L?this.g=[this.g,b]:a.push(b)};n.S=function(a){var b=this.c;b.constructor===L||1===b.length?this.c=void 0:b[b.indexOf(a)]=b.pop()};n.T=function(a){var b=this.g;b.constructor===L||1===b.length?this.g=void 0:b[b.indexOf(a)]=b.pop()};
function ea(a){var b=a.g;if(void 0!==b)if(b.constructor===L)b.O.T(b);else for(var d=0;d<b.length;d++){var c=b[d];c.O.T(c)}a.g=void 0}function ga(){var a=document.getElementById("todoapp"),b=y(ha,void 0,void 0);I().write(function(){a.appendChild(b.element);b.K();b.update()})}function V(a,b){this.path=a;this.U=b}
function ia(a,b){if(""!==b&&"#"===b[0])if("!"===b[1])b=b.substr(2);else return!1;for(var d=0;d<a.length;d++){var c=a[d],e=c.path;if("string"===typeof e){if(b===e)return c.U(),!0}else if(e=b.match(e))return 1<e.length?c.U(e.slice(1)):c.U(),!0}return!1}function ja(){this.a=0;this.m=new P}function Entry(a,b,d){this.id=a.toString();this.title=b;this.C=d;this.m=new P}function ka(){this.a=void 0;this.title="";this.m=new P}function la(){this.a=[];this.c=new P;this.m=new P}
function ma(){this.a=this.c=0;this.g=new P;this.l=new P;this.m=new P}function W(a){var b=X;b.l.a=a;b.l.m.i()}function na(a,b){for(var d=a.c.a,c=0;c<d.length;c++){var e=d[c];if(e===b){d.splice(c,1);a.c.m.i();d=a.a;d.c--;d.g.i();e.C&&(d.a--,d.l.i());d.m.i();break}}}function Y(){var a=X;a.g.a=void 0;a.g.title="";a.g.m.i()}
var X=new function(){this.l=new ja;this.a=new ma;this.c=new la;this.g=new ka;this.G=0},oa=T((new S).tagName("header"),function(a){a.state="";a.element.addEventListener("keydown",function(b){if(13===b.keyCode&&"new-todo"===b.target.id){b=a.state;var d=X;b=b.trim();""!==b&&(d.c.a.push(new Entry(d.G++,b,!1)),d.c.m.i(),d.a.c++,d.a.g.i(),d.a.m.i());a.state="";a.i()}});a.element.addEventListener("input",function(b){"new-todo"===b.target.id&&(a.state=b.target.value,a.i())})}).update(function(a){a.u(D().children([C("h1").children("todos"),
u(new t(514,"input",void 0),{id:"new-todo",type:"text",placeholder:"What needs to be done",autofocus:!0}).value(a.state)]))}),Z=T(function(){var a=(new S).tagName("li");a.b|=1;return a}(),function(a){a.subscribe(a.data.m);a.state=!1}).update(function(a){var b=a.data,d=X.g.a===b,c=C("div").className("view").children([v((new t(1026,"input",void 0)).className("toggle"),{type:"checkbox"}).checked(b.C),C("label").children(b.title),C("button").className("destroy")]);d?(a.P(X.g.m),b=b.C?"editing completed":
"editing",d=v((new t(514,"input",void 0)).className("edit"),{type:"text"}).value(X.g.title),a.state||(a.state=!0,K.g.focus(d)),c=[c,d]):(a.state=!1,b=b.C?"completed":void 0,c=[c]);a.u(D().className(b).children(c))}),pa=T((new S).tagName("ul"),function(a){a.subscribe(X.l.m);a.subscribe(X.c.m);a.element.addEventListener("keydown",function(a){if(a.target.classList.contains("edit"))if(13===a.keyCode){a=a.target.parentNode.R.data;var d=X,c=X.g.title,c=c.trim();""===c?na(d,a):(a.title=c,a.m.i());Y()}else 27===
a.keyCode&&Y()});a.element.addEventListener("dblclick",function(a){if("LABEL"===a.target.tagName){a=a.target.parentNode.parentNode.R;var d=a.data,c=X;c.g.a=d;c.g.title=d.title;c.g.m.i();a.i()}});a.element.addEventListener("focusout",function(a){a.target.classList.contains("edit")&&Y()});a.element.addEventListener("click",function(a){a.target.classList.contains("destroy")&&na(X,a.target.parentNode.parentNode.R.data)});a.element.addEventListener("change",function(a){if(a.target.classList.contains("toggle")){a=
a.target.parentNode.parentNode.R.data;var d=X,c=d.a;a.C?(a.C=!1,c.a--):(a.C=!0,c.a++);d.c.c.i();a.m.i();c.l.i();c.m.i()}});a.element.addEventListener("input",function(a){if(a.target.classList.contains("edit")){a=a.target.value;var d=X;d.g.title!==a&&(d.g.title=a,d.g.m.i())}})}).update(function(a){var b=X.a,d=X.l.a,c=X.c.a,e,g;if(1===d)if(a.P(X.c.c),b=b.c-b.a,0===b)b=[];else for(b=Array(b),e=g=0;e<c.length;e++)d=c[e],d.C||(b[g++]=U(Z,d).key(d.id));else if(2===d)if(a.P(X.c.c),0===b.a)b=[];else for(b=
Array(b.a),e=g=0;e<c.length;e++)d=c[e],d.C&&(b[g++]=U(Z,d).key(d.id));else for(b=Array(c.length),e=0;e<c.length;e++)d=c[e],b[e]=U(Z,d).key(d.id);a.u(aa(u(D(),{id:"todo-list"}),b),2)}),qa=T((new S).tagName("section"),function(a){a.subscribe(X.a.m);a.element.addEventListener("change",function(a){if("toggle-all"===a.target.id){var d=X,c=d.c.a,e=d.a,g=0,f,h;if(X.a.a!==X.a.c)for(f=0;f<c.length;f++)h=c[f],h.C||(h.C=!0,h.m.i(),g++);else for(f=0;f<c.length;f++)h=c[f],h.C&&(h.C=!1,h.m.i(),g--);0!==g&&(d.c.c.i(),
e.a+=g,e.l.i(),e.m.i())}a.stopPropagation();a.preventDefault()})}).update(function(a){a.u(u(D(),{id:"main"}).children([u(new t(1026,"input",void 0),{type:"checkbox",id:"toggle-all"}).checked(X.a.a===X.a.c),U(pa)]))}),ra=T((new S).tagName("footer"),function(a){a.subscribe(X.l.m);a.subscribe(X.a.m);a.element.addEventListener("click",function(a){if("clear-completed"===a.target.id){var d=X,c=d.a;if(0<c.a){for(var e=d.c.a,g=[],f=0;f<e.length;f++){var h=e[f];h.C||g.push(h)}d.c.a=g;d.c.m.i();c.c-=c.a;c.a=
0;c.l.i();c.g.i();c.m.i()}a.preventDefault();a.stopPropagation()}})}).update(function(a){var b=X.l.a,d=[];d.push(u(C("ul"),{id:"filters"}).children([C("li").children([u(C("a"),{href:"#!/"}).className(0===b?"selected":null).children("All")]),new t(1,void 0," "),C("li").children([u(C("a"),{href:"#!/active"}).className(1===b?"selected":null).children("Active")]),new t(1,void 0," "),C("li").children([u(C("a"),{href:"#!/completed"}).className(2===b?"selected":null).children("Completed")])]));var b=X.a.a,
c=X.a.c-b;d.push(u(C("span"),{id:"todo-count"}).children([C("strong").children(c.toString()),new t(1,void 0,1<c?" items left":" item left")]));0<b&&d.push(u(C("button"),{id:"clear-completed"}).children("Clear completed ("+b+")"));a.u(u(D(),{id:"footer"}).children(d))}),ha=T((new S).tagName("section"),function(a){a.subscribe(X.a.g)}).update(function(a){a.u(D().children(0<X.a.c?[U(oa),U(qa),U(ra)]:[U(oa)]))});
(function(a,b,d){b=void 0===b?"":b;var c=location,e=decodeURIComponent(c.hash);""===e&&(c.hash=e="#!"+b);window.addEventListener("hashchange",function(){var g=decodeURIComponent(c.hash);""===g&&(c.hash=e="#!"+b);e!==g&&(e=g,ia(a,g)||void 0!==d&&d())});ia(a,e)||void 0!==d&&d()})([new V("/completed",function(){W(2)}),new V("/active",function(){W(1)}),new V("/",function(){W(0)})]);document.addEventListener("DOMContentLoaded",function(){ga()});}).call();
